### ISSUE TITLE
SQLインジェクションが可能

### ISSUE THREAD

**Issue by suzukiplan** [hello-ty/beposi#1]
以下のコードですが、

https://github.com/hello-ty/beposi/blob/bd8b743b7fdf4bf4d0832809b167dd0ed5552dc1/app/routes/search.js#L12

クエリパラメタで与えられた `keyword` に SQL の構文を含めることで、外部から好きなようにデータベースを操作できる SQL インジェクションというセキュリティ脆弱があるので、対策した方が良いですね。

参考: https://www.kagoya.jp/howto/it-glossary/security/sql-injection/

**Comment by hello-ty** [comment]
対策しました

**Comment by suzukiplan** [comment]
対策した commit や PullRequest を貼りましょう

**Comment by suzukiplan** [comment]
issue に対して Pull Request を貼るのが多分一般的です（別途例をSlackで送っておきます）

**Comment by hello-ty** [comment]
こちら対応したコミットになります。
https://github.com/hello-ty/beposi/commit/1ba1d3dd4f29d4087529cf45e5aad5b78466ad53
https://github.com/hello-ty/beposi/commit/1ba1d3dd4f29d4087529cf45e5aad5b78466ad53
